import React from "react";

export const routes = [
  {
    to: null,
    title: "Creación de componentes",
    description: "",
    component: React.lazy(() => import("../pages/Home")),
  },
  {
    to: "Ejem1",
    title: "Componente usando clases",
    description: "Muestra como crear un componente usando clases. Obsoleto.",
    component: React.lazy(() => import("../pages/Ejem_01")),
  },
  {
    to: "Ejem2",
    title: "Componentes dentro de otros componentes",
    description: "Uso de componetnes anidados",
    component: React.lazy(() => import("../pages/Ejem_02")),
  },
  {
    to: "Ejem3",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_03")),
  },
  {
    to: "Ejem4",
    title: "Props",
    description: "paso de props al componente",
    component: React.lazy(() => import("../pages/Ejem_04")),
  },
  {
    to: "Ejem5",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_05")),
  },
  {
    to: "Ejem6",
    title: "Comunicacion hijo a padre",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_06")),
  },
  {
    to: "Ejem7",
    title: "Hook useState",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_07")),
  },
  {
    to: "Ejem8",
    title: "Pasar los hijos de un componente",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_08")),
  },
  {
    to: "Ejem9",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_09")),
  },
  {
    to: "Ejem10",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_10")),
  },
  {
    to: "Ejem11",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_11")),
  },
  {
    to: "Ejem12",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_12")),
  },
  {
    to: "Ejem13",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_13")),
  },
  {
    to: "Ejem14",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_14")),
  },
  {
    to: "Ejem15",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_15")),
  },
  {
    to: "Ejem16",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_16")),
  },
  {
    to: "Ejem17",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_17")),
  },
  {
    to: "Ejem18",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_18")),
  },
  {
    to: "Ejem19",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_19")),
  },
  {
    to: "Ejem20",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_20")),
  },
  {
    to: "Ejem21",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_21")),
  },
  {
    to: "Ejem22",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_22")),
  },
  {
    to: "Ejem23",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_23")),
  },
  {
    to: "Ejem24",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejem_24")),
  },
  {
    to: "Ejercicio1",
    title: "Mostrar valor en grados y centigrados",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_01")),
  },

  {
    to: "Ejercicio2",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_02")),
  },
  {
    to: "Ejercicio3",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_03")),
  },
  {
    to: "Ejercicio4",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_04")),
  },
  {
    to: "Ejercicio5",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_05")),
  },
  {
    to: "Ejercicio6",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_06")),
  },
  {
    to: "Ejercicio7",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_07")),
  },
  {
    to: "Ejercicio8",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_08")),
  },
  {
    to: "Ejercicio9",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_09")),
  },
  {
    to: "Ejercicio10",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_10")),
  },
  {
    to: "Ejercicio11",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_11")),
  },
  {
    to: "Ejercicio12",
    title: "",
    description: "",
    component: React.lazy(() => import("../pages/Ejercicio_12")),
  },

];